### ISSUE TITLE
Incorrect lat/lon/UTMzone for 2014 Napa Valley earthquake case

### ISSUE THREAD

**Issue by jiangyuinsar** [ruthamey/slipBERI#1]
Hi Ruth,

I noticed that the location of EQ epicentre in Napa earthquake and its corresponding UTM zone are incorrect. I guess this is the information in Japan Tottori earthquake.
Please have a look at this file, /slipBERI/examples/napa_valley_earthqukae/make_default_structure_napa.m

Yu

**Comment by ruthamey** [comment]
Hi Yu,

Thanks for spotting that and letting me know. I’ve updated it now.

Ruth

---

Dr. Ruth Amey
Postdoctoral Researcher
Institute of Geophysics & Tectonics
School of Earth and Environment
University of Leeds
Leeds, LS2 9JT
Twitter: @ruthamey

**Comment by jiangyuinsar** [comment]
Hi Ruth,

Great! Many thanks for that.

Yu
